# Generated by Django 3.0.1 on 2020-01-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complite',
            new_name='complete',
        ),
    ]
